services:
  kmir:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    container_name: kmir
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env

  postgres:
    image: 'postgres:16.0'
    container_name: kmir_postgres
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
